Update network settings

diff --git a/home/res/bin/siemens_remote b/home/res/bin/siemens_remote
--- a/home/res/bin/siemens_remote
+++ b/home/res/bin/siemens_remote
@@ -6,71 +6,55 @@ HOST=${2:-artifacts.mobility.siemens.com}
 DNS=172.31.1.1
 GW=${DNS}
 
-wait_for_zgw(){
-  printf 'Waiting for DNS:'
+wait_for_zgw() {
+    printf 'Waiting for DNS:'
     while ! nslookup "$HOST" "$DNS" >/dev/null 2>&1; do
-    printf '.'
-    sleep 3s
-  done
-  printf 'DNS Resolution completed'
-  echo 'OK'
+        printf '.'
+        sleep 3s
+    done
+    printf 'DNS Resolution completed'
+    echo 'OK'
 }
 
-routing(){
-  set -x
-  [ "$DGW" = '10.165.16.1' ] && ip route "$1" 10.165.0.0/16 via "$DGW"
-  ip route "$1" 10.0.0.0/8 via "$GW"
-  ip route "$1" 100.64.0.0/10 via "$GW"
-  ip route "$1" 149.212.0.0/16 via "$GW"
-  ip route "$1" 143.204.0.0/16 via "$GW"
-  ip route "$1" 3.0.0.0/9 via "$GW"
-  ip route "$1" 52.0.0.0/10 via "$GW"
-  ip route "$1" 52.64.0.0/12 via "$GW"
-  ip route "$1" 10.80.2.11 via 217.74.214.251
-  ip route "$1" 52.59.56.222 via "$DGW"
-  ip route "$1" 212.98.116.57 via "$GW"
-  ip route "$1" 129.103.0.0/16 via "$GW"
-  set +x
-}
-
-dnsmasq_conf(){
-  cat << EOF
-server=/siemens.net/${DNS}
-server=/siemens.com/${DNS}
-server=/siemens.io/${DNS}
-server=/siemens.de/${DNS}
-server=/siemens.dk/${DNS}
-server=/mobnet.dk/${DNS}
-EOF
+routing() {
+    set -x
+    [ "$DGW" = '10.165.16.1' ] && ip route "$1" 10.165.0.0/16 via "$DGW"
+    ip route "$1" 10.0.0.0/8 via "$GW"
+    ip route "$1" 100.64.0.0/10 via "$GW"
+    ip route "$1" 149.212.0.0/16 via "$GW"
+    ip route "$1" 143.204.0.0/16 via "$GW"
+    ip route "$1" 3.0.0.0/9 via "$GW"
+    ip route "$1" 52.0.0.0/10 via "$GW"
+    ip route "$1" 52.64.0.0/12 via "$GW"
+    ip route "$1" 10.80.2.11 via 217.74.214.251
+    ip route "$1" 52.59.56.222 via "$DGW"
+    ip route "$1" 212.98.116.57 via "$GW"
+    ip route "$1" 129.103.0.0/16 via "$GW"
+    set +x
 }
 
 resolv_conf() {
-  cat <<EOF
+    cat <<EOF
 nameserver 127.0.0.1
 nameserver 8.8.8.8
 EOF
 }
 
-
 case $1 in
 up | down)
-  [ "$(id -u)" -eq 0 ] || exec sudo "$0" "$@"
-  case $1 in
-  up)
-    wait_for_zgw
-    routing add
-    dnsmasq_conf > /run/dnsmasq/siemens.conf
+    [ "$(id -u)" -eq 0 ] || exec sudo "$0" "$@"
+    case $1 in
+    up)
+        wait_for_zgw
+        routing add
+        ;;
+    down)
+        routing del
+        ;;
+    esac
     ;;
-  down)
-    routing del
-    rm /run/dnsmasq/siemens.conf
-    ;;
-  esac
-  ;;
 *)
-  echo 'Argument [up|down] required!'
-  exit 1
-  ;;
+    echo 'Argument [up|down] required!'
+    exit 1
+    ;;
 esac
-sudo systemctl restart dnsmasq.service
-sudo systemctl restart dnsmasq@nat0.service
